[package]
name = "mikesaltveit/parentscheduleapp"
version = "0.7.2"
description = "Parent Schedule App"

[dependencies]
"php/php" = "8.*"

[fs]
"/app" = "public"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-S", "localhost:8080", "-t", "/app"]
